// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_nomad_upload_files_for_nomadSchema = {
    properties: {
        experiment_id: {
            type: 'string',
            title: 'Experiment Id'
        },
        experiment_name: {
            type: 'string',
            title: 'Experiment Name'
        },
        files: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['experiment_id', 'experiment_name', 'files'],
    title: 'Body_nomad-upload_files_for_nomad'
} as const;

export const Body_nomad_upload_to_nomad_endpointSchema = {
    properties: {
        request: {
            '$ref': '#/components/schemas/NomadUploadRequest'
        },
        files: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'binary'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Files'
        }
    },
    type: 'object',
    required: ['request'],
    title: 'Body_nomad-upload_to_nomad_endpoint'
} as const;

export const BulkStateResponseSchema = {
    properties: {
        materials: {
            items: {
                '$ref': '#/components/schemas/MaterialPublic'
            },
            type: 'array',
            title: 'Materials'
        },
        solutions: {
            items: {
                '$ref': '#/components/schemas/SolutionPublic'
            },
            type: 'array',
            title: 'Solutions'
        },
        experiments: {
            items: {
                '$ref': '#/components/schemas/ExperimentPublic'
            },
            type: 'array',
            title: 'Experiments'
        },
        results: {
            items: {
                '$ref': '#/components/schemas/ExperimentResultsPublic'
            },
            type: 'array',
            title: 'Results'
        },
        planes: {
            items: {
                '$ref': '#/components/schemas/PlanePublic'
            },
            type: 'array',
            title: 'Planes'
        }
    },
    type: 'object',
    required: ['materials', 'solutions', 'experiments', 'results', 'planes'],
    title: 'BulkStateResponse',
    description: 'Full application state for bulk loading.'
} as const;

export const CanvasElementCreateSchema = {
    properties: {
        element_type: {
            type: 'string',
            maxLength: 50,
            title: 'Element Type'
        },
        x: {
            type: 'number',
            title: 'X',
            default: 0
        },
        y: {
            type: 'number',
            title: 'Y',
            default: 0
        },
        width: {
            type: 'number',
            title: 'Width',
            default: 100
        },
        height: {
            type: 'number',
            title: 'Height',
            default: 100
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        }
    },
    type: 'object',
    required: ['element_type'],
    title: 'CanvasElementCreate'
} as const;

export const CanvasElementPublicSchema = {
    properties: {
        element_type: {
            type: 'string',
            maxLength: 50,
            title: 'Element Type'
        },
        x: {
            type: 'number',
            title: 'X',
            default: 0
        },
        y: {
            type: 'number',
            title: 'Y',
            default: 0
        },
        width: {
            type: 'number',
            title: 'Width',
            default: 100
        },
        height: {
            type: 'number',
            title: 'Height',
            default: 100
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['element_type', 'id'],
    title: 'CanvasElementPublic'
} as const;

export const DeviceGroupCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        substrate_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Substrate Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DeviceGroupCreate'
} as const;

export const DeviceGroupInfoSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        deviceName: {
            type: 'string',
            title: 'Devicename'
        },
        assignedSubstrateId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignedsubstrateid'
        },
        files: {
            items: {
                '$ref': '#/components/schemas/MeasurementFileInfo'
            },
            type: 'array',
            title: 'Files',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'deviceName'],
    title: 'DeviceGroupInfo',
    description: 'Device group info for NOMAD upload.'
} as const;

export const DeviceGroupPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        substrate_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Substrate Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'DeviceGroupPublic'
} as const;

export const ExperimentCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        device_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Type'
        },
        active_area_cm2: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active Area Cm2'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        substrates: {
            items: {
                '$ref': '#/components/schemas/SubstrateCreate'
            },
            type: 'array',
            title: 'Substrates',
            default: []
        },
        layers: {
            items: {
                '$ref': '#/components/schemas/ExperimentLayerCreate'
            },
            type: 'array',
            title: 'Layers',
            default: []
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ExperimentCreate'
} as const;

export const ExperimentLayerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        layer_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Layer Type'
        },
        material_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Material Id'
        },
        solution_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Solution Id'
        },
        temperature: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Temperature'
        },
        temperature_unit: {
            type: 'string',
            maxLength: 50,
            title: 'Temperature Unit',
            default: '°C'
        },
        duration: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration'
        },
        duration_unit: {
            type: 'string',
            maxLength: 50,
            title: 'Duration Unit',
            default: 'min'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ExperimentLayerCreate'
} as const;

export const ExperimentLayerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        layer_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Layer Type'
        },
        material_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Material Id'
        },
        solution_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Solution Id'
        },
        temperature: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Temperature'
        },
        temperature_unit: {
            type: 'string',
            maxLength: 50,
            title: 'Temperature Unit',
            default: '°C'
        },
        duration: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration'
        },
        duration_unit: {
            type: 'string',
            maxLength: 50,
            title: 'Duration Unit',
            default: 'min'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ExperimentLayerPublic'
} as const;

export const ExperimentPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        device_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Type'
        },
        active_area_cm2: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active Area Cm2'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        substrates: {
            items: {
                '$ref': '#/components/schemas/SubstratePublic'
            },
            type: 'array',
            title: 'Substrates'
        },
        layers: {
            items: {
                '$ref': '#/components/schemas/ExperimentLayerPublic'
            },
            type: 'array',
            title: 'Layers'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'substrates', 'layers'],
    title: 'ExperimentPublic'
} as const;

export const ExperimentResultsCreateSchema = {
    properties: {
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        measurement_files: {
            items: {
                '$ref': '#/components/schemas/MeasurementFileCreate'
            },
            type: 'array',
            title: 'Measurement Files',
            default: []
        },
        device_groups: {
            items: {
                '$ref': '#/components/schemas/DeviceGroupCreate'
            },
            type: 'array',
            title: 'Device Groups',
            default: []
        }
    },
    type: 'object',
    title: 'ExperimentResultsCreate'
} as const;

export const ExperimentResultsListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExperimentResultsPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExperimentResultsListPublic'
} as const;

export const ExperimentResultsPublicSchema = {
    properties: {
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        experiment_id: {
            type: 'string',
            format: 'uuid',
            title: 'Experiment Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        measurement_files: {
            items: {
                '$ref': '#/components/schemas/MeasurementFilePublic'
            },
            type: 'array',
            title: 'Measurement Files'
        },
        device_groups: {
            items: {
                '$ref': '#/components/schemas/DeviceGroupPublic'
            },
            type: 'array',
            title: 'Device Groups'
        }
    },
    type: 'object',
    required: ['id', 'experiment_id', 'owner_id', 'measurement_files', 'device_groups'],
    title: 'ExperimentResultsPublic'
} as const;

export const ExperimentResultsUpdateSchema = {
    properties: {
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'ExperimentResultsUpdate'
} as const;

export const ExperimentUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        device_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Type'
        },
        active_area_cm2: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active Area Cm2'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'ExperimentUpdate'
} as const;

export const ExperimentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ExperimentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ExperimentsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MaterialCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        cas_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cas Number'
        },
        molecular_weight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Molecular Weight'
        },
        density: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Density'
        },
        density_unit: {
            type: 'string',
            maxLength: 50,
            title: 'Density Unit',
            default: 'g/cm3'
        },
        supplier: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'MaterialCreate'
} as const;

export const MaterialPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        cas_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cas Number'
        },
        molecular_weight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Molecular Weight'
        },
        density: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Density'
        },
        density_unit: {
            type: 'string',
            maxLength: 50,
            title: 'Density Unit',
            default: 'g/cm3'
        },
        supplier: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id'],
    title: 'MaterialPublic'
} as const;

export const MaterialUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        cas_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cas Number'
        },
        molecular_weight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Molecular Weight'
        },
        density: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Density'
        },
        density_unit: {
            type: 'string',
            maxLength: 50,
            title: 'Density Unit',
            default: 'g/cm3'
        },
        supplier: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'MaterialUpdate'
} as const;

export const MaterialsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MaterialPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MaterialsPublic'
} as const;

export const MeasurementFileCreateSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Filename'
        },
        file_type: {
            type: 'string',
            maxLength: 50,
            title: 'File Type'
        },
        file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Path'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['filename', 'file_type'],
    title: 'MeasurementFileCreate'
} as const;

export const MeasurementFileInfoSchema = {
    properties: {
        fileName: {
            type: 'string',
            title: 'Filename'
        },
        fileType: {
            type: 'string',
            title: 'Filetype'
        },
        deviceName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Devicename'
        },
        cell: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cell'
        },
        pixel: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pixel'
        },
        value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value'
        }
    },
    type: 'object',
    required: ['fileName', 'fileType'],
    title: 'MeasurementFileInfo',
    description: 'Measurement file metadata for NOMAD upload.'
} as const;

export const MeasurementFilePublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Filename'
        },
        file_type: {
            type: 'string',
            maxLength: 50,
            title: 'File Type'
        },
        file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Path'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['filename', 'file_type', 'id'],
    title: 'MeasurementFilePublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NomadConfigResponseSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        use_global_auth: {
            type: 'boolean',
            title: 'Use Global Auth'
        },
        has_credentials: {
            type: 'boolean',
            title: 'Has Credentials'
        }
    },
    type: 'object',
    required: ['enabled', 'url', 'use_global_auth', 'has_credentials'],
    title: 'NomadConfigResponse',
    description: 'NOMAD configuration status.'
} as const;

export const NomadMetadataPreviewSchema = {
    properties: {
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        metadata_yaml: {
            type: 'string',
            title: 'Metadata Yaml'
        },
        yaml_content: {
            type: 'string',
            title: 'Yaml Content'
        },
        file_count: {
            type: 'integer',
            title: 'File Count'
        },
        device_group_count: {
            type: 'integer',
            title: 'Device Group Count'
        }
    },
    type: 'object',
    required: ['metadata_json', 'metadata_yaml', 'yaml_content', 'file_count', 'device_group_count'],
    title: 'NomadMetadataPreview',
    description: 'Preview of NOMAD metadata.'
} as const;

export const NomadUploadRequestSchema = {
    properties: {
        experiment_id: {
            type: 'string',
            title: 'Experiment Id'
        },
        experiment_name: {
            type: 'string',
            title: 'Experiment Name'
        },
        substrates: {
            items: {
                '$ref': '#/components/schemas/SubstrateInfo'
            },
            type: 'array',
            title: 'Substrates',
            default: []
        },
        measurement_files: {
            items: {
                '$ref': '#/components/schemas/MeasurementFileInfo'
            },
            type: 'array',
            title: 'Measurement Files',
            default: []
        },
        device_groups: {
            items: {
                '$ref': '#/components/schemas/DeviceGroupInfo'
            },
            type: 'array',
            title: 'Device Groups',
            default: []
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        custom_metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Metadata'
        }
    },
    type: 'object',
    required: ['experiment_id', 'experiment_name'],
    title: 'NomadUploadRequest',
    description: 'Request body for NOMAD upload.'
} as const;

export const NomadUploadResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        upload_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Upload Id'
        },
        entry_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Entry Ids',
            default: []
        },
        upload_create_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Upload Create Time'
        },
        processing_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Status'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'NomadUploadResponse',
    description: 'Response from NOMAD upload.'
} as const;

export const NomadUploadStatusSchema = {
    properties: {
        upload_id: {
            type: 'string',
            title: 'Upload Id'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        entries: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Entries',
            default: []
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['upload_id'],
    title: 'NomadUploadStatus',
    description: 'Status of a NOMAD upload.'
} as const;

export const PlaneCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        elements: {
            items: {
                '$ref': '#/components/schemas/CanvasElementCreate'
            },
            type: 'array',
            title: 'Elements',
            default: []
        }
    },
    type: 'object',
    required: ['name'],
    title: 'PlaneCreate'
} as const;

export const PlanePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        elements: {
            items: {
                '$ref': '#/components/schemas/CanvasElementPublic'
            },
            type: 'array',
            title: 'Elements'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'elements'],
    title: 'PlanePublic'
} as const;

export const PlaneUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'PlaneUpdate'
} as const;

export const PlanesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlanePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlanesPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SolutionComponentCreateSchema = {
    properties: {
        amount: {
            type: 'number',
            title: 'Amount'
        },
        unit: {
            type: 'string',
            maxLength: 50,
            title: 'Unit'
        },
        material_id: {
            type: 'string',
            format: 'uuid',
            title: 'Material Id'
        }
    },
    type: 'object',
    required: ['amount', 'unit', 'material_id'],
    title: 'SolutionComponentCreate'
} as const;

export const SolutionComponentPublicSchema = {
    properties: {
        amount: {
            type: 'number',
            title: 'Amount'
        },
        unit: {
            type: 'string',
            maxLength: 50,
            title: 'Unit'
        },
        material_id: {
            type: 'string',
            format: 'uuid',
            title: 'Material Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['amount', 'unit', 'material_id', 'id'],
    title: 'SolutionComponentPublic'
} as const;

export const SolutionCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        components: {
            items: {
                '$ref': '#/components/schemas/SolutionComponentCreate'
            },
            type: 'array',
            title: 'Components',
            default: []
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SolutionCreate'
} as const;

export const SolutionPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        components: {
            items: {
                '$ref': '#/components/schemas/SolutionComponentPublic'
            },
            type: 'array',
            title: 'Components'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'components'],
    title: 'SolutionPublic'
} as const;

export const SolutionUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'SolutionUpdate'
} as const;

export const SolutionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SolutionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SolutionsPublic'
} as const;

export const SubstrateCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        thickness_nm: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thickness Nm'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SubstrateCreate'
} as const;

export const SubstrateInfoSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'SubstrateInfo',
    description: 'Substrate info for NOMAD upload.'
} as const;

export const SubstratePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        thickness_nm: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thickness Nm'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'SubstratePublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserStatePublicSchema = {
    properties: {
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'UserStatePublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;