// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_nomad_upload_files_for_nomad = {
    experiment_id: string;
    experiment_name: string;
    files: Array<((Blob | File))>;
};

export type Body_nomad_upload_to_nomad_endpoint = {
    request: NomadUploadRequest;
    files?: (Array<((Blob | File))> | null);
};

/**
 * Full application state for bulk loading.
 */
export type BulkStateResponse = {
    materials: Array<MaterialPublic>;
    solutions: Array<SolutionPublic>;
    experiments: Array<ExperimentPublic>;
    results: Array<ExperimentResultsPublic>;
    planes: Array<PlanePublic>;
};

export type CanvasElementCreate = {
    element_type: string;
    x?: number;
    y?: number;
    width?: number;
    height?: number;
    content?: (string | null);
    color?: (string | null);
};

export type CanvasElementPublic = {
    element_type: string;
    x?: number;
    y?: number;
    width?: number;
    height?: number;
    content?: (string | null);
    color?: (string | null);
    id: string;
};

export type DeviceGroupCreate = {
    name: string;
    substrate_name?: (string | null);
};

/**
 * Device group info for NOMAD upload.
 */
export type DeviceGroupInfo = {
    id: string;
    deviceName: string;
    assignedSubstrateId?: (string | null);
    files?: Array<MeasurementFileInfo>;
};

export type DeviceGroupPublic = {
    name: string;
    substrate_name?: (string | null);
    id: string;
};

export type ExperimentCreate = {
    name: string;
    description?: (string | null);
    device_type?: (string | null);
    active_area_cm2?: (number | null);
    notes?: (string | null);
    substrates?: Array<SubstrateCreate>;
    layers?: Array<ExperimentLayerCreate>;
};

export type ExperimentLayerCreate = {
    name: string;
    layer_type?: (string | null);
    material_id?: (string | null);
    solution_id?: (string | null);
    temperature?: (number | null);
    temperature_unit?: string;
    duration?: (number | null);
    duration_unit?: string;
    notes?: (string | null);
};

export type ExperimentLayerPublic = {
    name: string;
    layer_type?: (string | null);
    material_id?: (string | null);
    solution_id?: (string | null);
    temperature?: (number | null);
    temperature_unit?: string;
    duration?: (number | null);
    duration_unit?: string;
    notes?: (string | null);
    id: string;
};

export type ExperimentPublic = {
    name: string;
    description?: (string | null);
    device_type?: (string | null);
    active_area_cm2?: (number | null);
    notes?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    substrates: Array<SubstratePublic>;
    layers: Array<ExperimentLayerPublic>;
};

export type ExperimentResultsCreate = {
    notes?: (string | null);
    measurement_files?: Array<MeasurementFileCreate>;
    device_groups?: Array<DeviceGroupCreate>;
};

export type ExperimentResultsListPublic = {
    data: Array<ExperimentResultsPublic>;
    count: number;
};

export type ExperimentResultsPublic = {
    notes?: (string | null);
    id: string;
    experiment_id: string;
    owner_id: string;
    created_at?: (string | null);
    measurement_files: Array<MeasurementFilePublic>;
    device_groups: Array<DeviceGroupPublic>;
};

export type ExperimentResultsUpdate = {
    notes?: (string | null);
};

export type ExperimentsPublic = {
    data: Array<ExperimentPublic>;
    count: number;
};

export type ExperimentUpdate = {
    name?: (string | null);
    description?: (string | null);
    device_type?: (string | null);
    active_area_cm2?: (number | null);
    notes?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MaterialCreate = {
    name: string;
    cas_number?: (string | null);
    molecular_weight?: (number | null);
    density?: (number | null);
    density_unit?: string;
    supplier?: (string | null);
    notes?: (string | null);
};

export type MaterialPublic = {
    name: string;
    cas_number?: (string | null);
    molecular_weight?: (number | null);
    density?: (number | null);
    density_unit?: string;
    supplier?: (string | null);
    notes?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type MaterialsPublic = {
    data: Array<MaterialPublic>;
    count: number;
};

export type MaterialUpdate = {
    name?: (string | null);
    cas_number?: (string | null);
    molecular_weight?: (number | null);
    density?: (number | null);
    density_unit?: string;
    supplier?: (string | null);
    notes?: (string | null);
};

export type MeasurementFileCreate = {
    filename: string;
    file_type: string;
    file_path?: (string | null);
    notes?: (string | null);
};

/**
 * Measurement file metadata for NOMAD upload.
 */
export type MeasurementFileInfo = {
    fileName: string;
    fileType: string;
    deviceName?: (string | null);
    cell?: (string | null);
    pixel?: (string | null);
    value?: (number | null);
};

export type MeasurementFilePublic = {
    filename: string;
    file_type: string;
    file_path?: (string | null);
    notes?: (string | null);
    id: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * NOMAD configuration status.
 */
export type NomadConfigResponse = {
    enabled: boolean;
    url: string;
    use_global_auth: boolean;
    has_credentials: boolean;
};

/**
 * Preview of NOMAD metadata.
 */
export type NomadMetadataPreview = {
    metadata_json: {
        [key: string]: unknown;
    };
    yaml_content: string;
    file_count: number;
    device_group_count: number;
};

/**
 * Request body for NOMAD upload.
 */
export type NomadUploadRequest = {
    experiment_id: string;
    experiment_name: string;
    substrates?: Array<SubstrateInfo>;
    measurement_files?: Array<MeasurementFileInfo>;
    device_groups?: Array<DeviceGroupInfo>;
    notes?: (string | null);
    custom_metadata?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Response from NOMAD upload.
 */
export type NomadUploadResponse = {
    success: boolean;
    upload_id?: (string | null);
    entry_ids?: Array<(string)>;
    upload_create_time?: (string | null);
    processing_status?: (string | null);
    message?: (string | null);
};

/**
 * Status of a NOMAD upload.
 */
export type NomadUploadStatus = {
    upload_id: string;
    status?: (string | null);
    entries?: Array<{
        [key: string]: unknown;
    }>;
    error?: (string | null);
};

export type PlaneCreate = {
    name: string;
    elements?: Array<CanvasElementCreate>;
};

export type PlanePublic = {
    name: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    elements: Array<CanvasElementPublic>;
};

export type PlanesPublic = {
    data: Array<PlanePublic>;
    count: number;
};

export type PlaneUpdate = {
    name?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SolutionComponentCreate = {
    amount: number;
    unit: string;
    material_id: string;
};

export type SolutionComponentPublic = {
    amount: number;
    unit: string;
    material_id: string;
    id: string;
};

export type SolutionCreate = {
    name: string;
    notes?: (string | null);
    components?: Array<SolutionComponentCreate>;
};

export type SolutionPublic = {
    name: string;
    notes?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    components: Array<SolutionComponentPublic>;
};

export type SolutionsPublic = {
    data: Array<SolutionPublic>;
    count: number;
};

export type SolutionUpdate = {
    name?: (string | null);
    notes?: (string | null);
};

export type SubstrateCreate = {
    name: string;
    thickness_nm?: (number | null);
};

/**
 * Substrate info for NOMAD upload.
 */
export type SubstrateInfo = {
    id: string;
    name: string;
};

export type SubstratePublic = {
    name: string;
    thickness_nm?: (number | null);
    id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserStatePublic = {
    data: {
        [key: string]: unknown;
    };
    updated_at?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ExperimentsReadExperimentsData = {
    limit?: number;
    skip?: number;
};

export type ExperimentsReadExperimentsResponse = (ExperimentsPublic);

export type ExperimentsCreateItemData = {
    requestBody: ExperimentCreate;
};

export type ExperimentsCreateItemResponse = (ExperimentPublic);

export type ExperimentsReadExperimentData = {
    id: string;
};

export type ExperimentsReadExperimentResponse = (ExperimentPublic);

export type ExperimentsUpdateItemData = {
    id: string;
    requestBody: ExperimentUpdate;
};

export type ExperimentsUpdateItemResponse = (ExperimentPublic);

export type ExperimentsDeleteExperimentData = {
    id: string;
};

export type ExperimentsDeleteExperimentResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MaterialsReadMaterialsData = {
    limit?: number;
    skip?: number;
};

export type MaterialsReadMaterialsResponse = (MaterialsPublic);

export type MaterialsCreateMaterialData = {
    requestBody: MaterialCreate;
};

export type MaterialsCreateMaterialResponse = (MaterialPublic);

export type MaterialsReadMaterialData = {
    id: string;
};

export type MaterialsReadMaterialResponse = (MaterialPublic);

export type MaterialsUpdateMaterialData = {
    id: string;
    requestBody: MaterialUpdate;
};

export type MaterialsUpdateMaterialResponse = (MaterialPublic);

export type MaterialsDeleteMaterialData = {
    id: string;
};

export type MaterialsDeleteMaterialResponse = (unknown);

export type NomadGetNomadConfigResponse = (NomadConfigResponse);

export type NomadPreviewNomadMetadataData = {
    requestBody: NomadUploadRequest;
};

export type NomadPreviewNomadMetadataResponse = (NomadMetadataPreview);

export type NomadUploadFilesForNomadData = {
    formData: Body_nomad_upload_files_for_nomad;
};

export type NomadUploadFilesForNomadResponse = ({
    [key: string]: unknown;
});

export type NomadUploadToNomadEndpointData = {
    archivePath?: (string | null);
    formData: Body_nomad_upload_to_nomad_endpoint;
};

export type NomadUploadToNomadEndpointResponse = (NomadUploadResponse);

export type NomadCheckUploadStatusData = {
    uploadId: string;
};

export type NomadCheckUploadStatusResponse = (NomadUploadStatus);

export type NomadTestNomadAuthResponse = ({
    [key: string]: unknown;
});

export type PlanesReadPlanesData = {
    limit?: number;
    skip?: number;
};

export type PlanesReadPlanesResponse = (PlanesPublic);

export type PlanesCreatePlaneData = {
    requestBody: PlaneCreate;
};

export type PlanesCreatePlaneResponse = (PlanePublic);

export type PlanesReadPlaneData = {
    id: string;
};

export type PlanesReadPlaneResponse = (PlanePublic);

export type PlanesUpdatePlaneData = {
    id: string;
    requestBody: PlaneUpdate;
};

export type PlanesUpdatePlaneResponse = (PlanePublic);

export type PlanesDeletePlaneData = {
    id: string;
};

export type PlanesDeletePlaneResponse = (unknown);

export type PlanesCreateElementData = {
    planeId: string;
    requestBody: CanvasElementCreate;
};

export type PlanesCreateElementResponse = (CanvasElementPublic);

export type PlanesUpdateElementData = {
    elementId: string;
    planeId: string;
    requestBody: CanvasElementCreate;
};

export type PlanesUpdateElementResponse = (CanvasElementPublic);

export type PlanesDeleteElementData = {
    elementId: string;
    planeId: string;
};

export type PlanesDeleteElementResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ResultsReadResultsData = {
    limit?: number;
    skip?: number;
};

export type ResultsReadResultsResponse = (ExperimentResultsListPublic);

export type ResultsCreateResultData = {
    experimentId: string;
    requestBody: ExperimentResultsCreate;
};

export type ResultsCreateResultResponse = (ExperimentResultsPublic);

export type ResultsReadResultData = {
    id: string;
};

export type ResultsReadResultResponse = (ExperimentResultsPublic);

export type ResultsUpdateResultData = {
    id: string;
    requestBody: ExperimentResultsUpdate;
};

export type ResultsUpdateResultResponse = (ExperimentResultsPublic);

export type ResultsDeleteResultData = {
    id: string;
};

export type ResultsDeleteResultResponse = (unknown);

export type SolutionsReadSolutionsData = {
    limit?: number;
    skip?: number;
};

export type SolutionsReadSolutionsResponse = (SolutionsPublic);

export type SolutionsCreateItemData = {
    requestBody: SolutionCreate;
};

export type SolutionsCreateItemResponse = (SolutionPublic);

export type SolutionsReadSolutionData = {
    id: string;
};

export type SolutionsReadSolutionResponse = (SolutionPublic);

export type SolutionsUpdateItemData = {
    id: string;
    requestBody: SolutionUpdate;
};

export type SolutionsUpdateItemResponse = (SolutionPublic);

export type SolutionsDeleteSolutionData = {
    id: string;
};

export type SolutionsDeleteSolutionResponse = (unknown);

export type StateReadStateResponse = (UserStatePublic);

export type StateUpdateStateData = {
    requestBody: UserStatePublic;
};

export type StateUpdateStateResponse = (UserStatePublic);

export type StateGetBulkStateResponse = (BulkStateResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);