"""Add nomad_sub and make hashed_password optional for OAuth users

Revision ID: 9c7054c6147b
Revises: c2f4a6b8d9e1
Create Date: 2026-05-05 10:37:45.693426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9c7054c6147b'
down_revision = 'c2f4a6b8d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nomad_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_nomad_sub'), 'user', ['nomad_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_nomad_sub'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'nomad_sub')
    # ### end Alembic commands ###
