"""add plane share table

Revision ID: a7b3c8d9e2f1
Revises: 1a31ce608336
Create Date: 2026-05-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7b3c8d9e2f1'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'planeshare',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('plane_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['plane_id'], ['plane.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planeshare_plane_id'), 'planeshare', ['plane_id'], unique=False)
    op.create_index(op.f('ix_planeshare_user_id'), 'planeshare', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planeshare_user_id'), table_name='planeshare')
    op.drop_index(op.f('ix_planeshare_plane_id'), table_name='planeshare')
    op.drop_table('planeshare')
    # ### end Alembic commands ###
